#:schema node_modules/wrangler/config-schema.json
#name = "cloudflare-astro-chatbot"
#compatibility_date = "2024-11-12"
#compatibility_flags = ["nodejs_compat_v2"]
#main = "./dist/_worker.js/index.js"
#assets = { directory = "./dist", binding = "ASSETS" }

node_compat = true

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true


[ai]
binding = "AI"


[[d1_databases]]
binding = "DB"
database_name = "chat-prod"
database_id = "6e9beb9c-7844-4727-b689-071349b0f8be"
preview_database_id = "DB"

# [env.preview]
# name = "preview"
# [[env.preview.d1_databases]]
# binding = "DB"
# database_name = "chat-preview"
# database_id = "f8d093b8-82ed-464a-91fc-e9bfee69bee1"
